### ISSUE TITLE
How do i make ardublock.jar in eclipse

### ISSUE THREAD

**Issue by GyuTae** [letsgoING/Arduino#1]
How do i make ardublock.jar in eclipse

**Comment by letsgoING** [comment]
You can use this instuction:
http://blog.ardublock.com/2012/06/11/setup-ardublock-development-in-eclipse/
Only use our block-masters, if you want so.
To export it just use the Eclipse export (File/Export -> Java/Runnable JAR file)

Or you can use the ardublock_all.jar File (letsgoING/ArduBlock/JAR).

Best regards
letsgoING
